version: '3.9'
services:
  postgres:
    image: postgres:16-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_BD_NAME:postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    container_name: app
    build: ./
    expose:
      - 3000:3000
    volumes:
      - ./dist
volumes:
  postgres:
    driver: local
